insert into class values (1, '1A')
insert into class values (2, '2A')
insert into class values (3, '1B')
insert into student values (1, 22, 'Edoardo', 'Lori', 1)
insert into student values (2, 25, 'Luana', 'Marchesi', 1)
insert into student values (3, 27, 'Marcello', 'Beneventi', 2)
insert into student values (4, 21, 'Maria', 'Cocci', 2)
insert into student values (5, 28, 'Eva', 'Pisano', 3)
insert into user values (1, '$2a$10$Gu2oqUmR94HntgrPdsw4dO3PiRSLgJslPT.IJ14BmtCvrRY9fgSD2', 'user')
insert into user values (2, '$2a$10$uOYtQyChet8.pmuDvt.i.eOtZcvdgJS7TlncbBoyH3Zb379S9Z41m', 'admin')
insert into role values (1, 'USER')
insert into role values (2, 'ADMIN')
insert into rel_user_role values (1, 1)
insert into rel_user_role values (2, 1)
insert into rel_user_role values (2, 2)

